/// <reference path="./custom.d.ts" />
// tslint:disable
/**
 * My Title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


import * as url from "url";
import * as portableFetch from "portable-fetch";
import { Configuration } from "./configuration";

const BASE_PATH = "https://checkme-app-api.azurewebsites.net".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

/**
 *
 * @export
 * @interface FetchAPI
 */
export interface FetchAPI {
    (url: string, init?: any): Promise<Response>;
}

/**
 *
 * @export
 * @interface FetchArgs
 */
export interface FetchArgs {
    url: string;
    options: any;
}

/**
 *
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
    protected configuration: Configuration;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected fetch: FetchAPI = portableFetch) {
        this.configuration = new Configuration();
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath || this.basePath;
        }
    }
};

/**
 *
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
    name="RequiredError"
    constructor(public field: string, msg?: string) {
        super(msg);
    }
}

/**
 * 
 * @export
 * @interface CheckList
 */
export interface CheckList {
    /**
     * 
     * @type {string}
     * @memberof CheckList
     */
    id: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CheckList
     */
    outstanding?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CheckList
     */
    done?: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof CheckList
     */
    timestamp: Date;
}

/**
 * 
 * @export
 * @enum {string}
 */
export enum ItemState {
    NUMBER_1 = <any> 1,
    NUMBER_2 = <any> 2
}

/**
 * 
 * @export
 * @interface ProblemDetails
 */
export interface ProblemDetails {
    [key: string]: any | any;

    /**
     * 
     * @type {string}
     * @memberof ProblemDetails
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof ProblemDetails
     */
    title?: string;
    /**
     * 
     * @type {number}
     * @memberof ProblemDetails
     */
    status?: number;
    /**
     * 
     * @type {string}
     * @memberof ProblemDetails
     */
    detail?: string;
    /**
     * 
     * @type {string}
     * @memberof ProblemDetails
     */
    instance?: string;
}

/**
 * 
 * @export
 * @interface WeatherForecast
 */
export interface WeatherForecast {
    /**
     * 
     * @type {Date}
     * @memberof WeatherForecast
     */
    date: Date;
    /**
     * 
     * @type {number}
     * @memberof WeatherForecast
     */
    temperatureC: number;
    /**
     * 
     * @type {number}
     * @memberof WeatherForecast
     */
    temperatureF: number;
    /**
     * 
     * @type {string}
     * @memberof WeatherForecast
     */
    summary?: string;
}


/**
 * ItemsApi - fetch parameter creator
 * @export
 */
export const ItemsApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} listId 
         * @param {string} item 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        itemsAddItem(listId: string, item: string, options: any = {}): FetchArgs {
            // verify required parameter 'listId' is not null or undefined
            if (listId === null || listId === undefined) {
                throw new RequiredError('listId','Required parameter listId was null or undefined when calling itemsAddItem.');
            }
            // verify required parameter 'item' is not null or undefined
            if (item === null || item === undefined) {
                throw new RequiredError('item','Required parameter item was null or undefined when calling itemsAddItem.');
            }
            const localVarPath = `/api/v1/lists/{listId}/items`
                .replace(`{${"listId"}}`, encodeURIComponent(String(listId)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'POST' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"string" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(item || {}) : (item || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} listId 
         * @param {string} oldItem 
         * @param {string} newItem 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        itemsEditItem(listId: string, oldItem: string, newItem: string, options: any = {}): FetchArgs {
            // verify required parameter 'listId' is not null or undefined
            if (listId === null || listId === undefined) {
                throw new RequiredError('listId','Required parameter listId was null or undefined when calling itemsEditItem.');
            }
            // verify required parameter 'oldItem' is not null or undefined
            if (oldItem === null || oldItem === undefined) {
                throw new RequiredError('oldItem','Required parameter oldItem was null or undefined when calling itemsEditItem.');
            }
            // verify required parameter 'newItem' is not null or undefined
            if (newItem === null || newItem === undefined) {
                throw new RequiredError('newItem','Required parameter newItem was null or undefined when calling itemsEditItem.');
            }
            const localVarPath = `/api/v1/lists/{listId}/items/{oldItem}`
                .replace(`{${"listId"}}`, encodeURIComponent(String(listId)))
                .replace(`{${"oldItem"}}`, encodeURIComponent(String(oldItem)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'PUT' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"string" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(newItem || {}) : (newItem || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} listId 
         * @param {string} item 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        itemsRemoveItem(listId: string, item: string, options: any = {}): FetchArgs {
            // verify required parameter 'listId' is not null or undefined
            if (listId === null || listId === undefined) {
                throw new RequiredError('listId','Required parameter listId was null or undefined when calling itemsRemoveItem.');
            }
            // verify required parameter 'item' is not null or undefined
            if (item === null || item === undefined) {
                throw new RequiredError('item','Required parameter item was null or undefined when calling itemsRemoveItem.');
            }
            const localVarPath = `/api/v1/lists/{listId}/items/{item}`
                .replace(`{${"listId"}}`, encodeURIComponent(String(listId)))
                .replace(`{${"item"}}`, encodeURIComponent(String(item)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'DELETE' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} listId 
         * @param {string} item 
         * @param {ItemState} state 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        itemsUpdateItem(listId: string, item: string, state: ItemState, options: any = {}): FetchArgs {
            // verify required parameter 'listId' is not null or undefined
            if (listId === null || listId === undefined) {
                throw new RequiredError('listId','Required parameter listId was null or undefined when calling itemsUpdateItem.');
            }
            // verify required parameter 'item' is not null or undefined
            if (item === null || item === undefined) {
                throw new RequiredError('item','Required parameter item was null or undefined when calling itemsUpdateItem.');
            }
            // verify required parameter 'state' is not null or undefined
            if (state === null || state === undefined) {
                throw new RequiredError('state','Required parameter state was null or undefined when calling itemsUpdateItem.');
            }
            const localVarPath = `/api/v1/lists/{listId}/items/{item}/state`
                .replace(`{${"listId"}}`, encodeURIComponent(String(listId)))
                .replace(`{${"item"}}`, encodeURIComponent(String(item)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'PUT' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"ItemState" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(state || {}) : (state || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ItemsApi - functional programming interface
 * @export
 */
export const ItemsApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} listId 
         * @param {string} item 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        itemsAddItem(listId: string, item: string, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<any> {
            const localVarFetchArgs = ItemsApiFetchParamCreator(configuration).itemsAddItem(listId, item, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @param {string} listId 
         * @param {string} oldItem 
         * @param {string} newItem 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        itemsEditItem(listId: string, oldItem: string, newItem: string, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<any> {
            const localVarFetchArgs = ItemsApiFetchParamCreator(configuration).itemsEditItem(listId, oldItem, newItem, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @param {string} listId 
         * @param {string} item 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        itemsRemoveItem(listId: string, item: string, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<any> {
            const localVarFetchArgs = ItemsApiFetchParamCreator(configuration).itemsRemoveItem(listId, item, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @param {string} listId 
         * @param {string} item 
         * @param {ItemState} state 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        itemsUpdateItem(listId: string, item: string, state: ItemState, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<any> {
            const localVarFetchArgs = ItemsApiFetchParamCreator(configuration).itemsUpdateItem(listId, item, state, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * ItemsApi - factory interface
 * @export
 */
export const ItemsApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * 
         * @param {string} listId 
         * @param {string} item 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        itemsAddItem(listId: string, item: string, options?: any) {
            return ItemsApiFp(configuration).itemsAddItem(listId, item, options)(fetch, basePath);
        },
        /**
         * 
         * @param {string} listId 
         * @param {string} oldItem 
         * @param {string} newItem 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        itemsEditItem(listId: string, oldItem: string, newItem: string, options?: any) {
            return ItemsApiFp(configuration).itemsEditItem(listId, oldItem, newItem, options)(fetch, basePath);
        },
        /**
         * 
         * @param {string} listId 
         * @param {string} item 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        itemsRemoveItem(listId: string, item: string, options?: any) {
            return ItemsApiFp(configuration).itemsRemoveItem(listId, item, options)(fetch, basePath);
        },
        /**
         * 
         * @param {string} listId 
         * @param {string} item 
         * @param {ItemState} state 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        itemsUpdateItem(listId: string, item: string, state: ItemState, options?: any) {
            return ItemsApiFp(configuration).itemsUpdateItem(listId, item, state, options)(fetch, basePath);
        },
    };
};

/**
 * ItemsApi - object-oriented interface
 * @export
 * @class ItemsApi
 * @extends {BaseAPI}
 */
export class ItemsApi extends BaseAPI {
    /**
     * 
     * @param {string} listId 
     * @param {string} item 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ItemsApi
     */
    public itemsAddItem(listId: string, item: string, options?: any) {
        return ItemsApiFp(this.configuration).itemsAddItem(listId, item, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @param {string} listId 
     * @param {string} oldItem 
     * @param {string} newItem 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ItemsApi
     */
    public itemsEditItem(listId: string, oldItem: string, newItem: string, options?: any) {
        return ItemsApiFp(this.configuration).itemsEditItem(listId, oldItem, newItem, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @param {string} listId 
     * @param {string} item 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ItemsApi
     */
    public itemsRemoveItem(listId: string, item: string, options?: any) {
        return ItemsApiFp(this.configuration).itemsRemoveItem(listId, item, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @param {string} listId 
     * @param {string} item 
     * @param {ItemState} state 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ItemsApi
     */
    public itemsUpdateItem(listId: string, item: string, state: ItemState, options?: any) {
        return ItemsApiFp(this.configuration).itemsUpdateItem(listId, item, state, options)(this.fetch, this.basePath);
    }

}

/**
 * ListsApi - fetch parameter creator
 * @export
 */
export const ListsApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {CheckList} list 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listsCreateList(list: CheckList, options: any = {}): FetchArgs {
            // verify required parameter 'list' is not null or undefined
            if (list === null || list === undefined) {
                throw new RequiredError('list','Required parameter list was null or undefined when calling listsCreateList.');
            }
            const localVarPath = `/api/v1/Lists`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'POST' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"CheckList" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(list || {}) : (list || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listsGetAllList(options: any = {}): FetchArgs {
            const localVarPath = `/api/v1/Lists`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} listId 
         * @param {Date} [timestamp] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listsGetList(listId: string, timestamp?: Date, options: any = {}): FetchArgs {
            // verify required parameter 'listId' is not null or undefined
            if (listId === null || listId === undefined) {
                throw new RequiredError('listId','Required parameter listId was null or undefined when calling listsGetList.');
            }
            const localVarPath = `/api/v1/Lists/{listId}`
                .replace(`{${"listId"}}`, encodeURIComponent(String(listId)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (timestamp !== undefined) {
                localVarQueryParameter['timestamp'] = (timestamp as any).toISOString();
            }

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} listId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listsGetListEvents(listId: string, options: any = {}): FetchArgs {
            // verify required parameter 'listId' is not null or undefined
            if (listId === null || listId === undefined) {
                throw new RequiredError('listId','Required parameter listId was null or undefined when calling listsGetListEvents.');
            }
            const localVarPath = `/api/v1/Lists/{listId}/events`
                .replace(`{${"listId"}}`, encodeURIComponent(String(listId)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} listId 
         * @param {CheckList} list 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listsUpdateList(listId: string, list: CheckList, options: any = {}): FetchArgs {
            // verify required parameter 'listId' is not null or undefined
            if (listId === null || listId === undefined) {
                throw new RequiredError('listId','Required parameter listId was null or undefined when calling listsUpdateList.');
            }
            // verify required parameter 'list' is not null or undefined
            if (list === null || list === undefined) {
                throw new RequiredError('list','Required parameter list was null or undefined when calling listsUpdateList.');
            }
            const localVarPath = `/api/v1/Lists/{listId}`
                .replace(`{${"listId"}}`, encodeURIComponent(String(listId)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'PUT' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"CheckList" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(list || {}) : (list || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ListsApi - functional programming interface
 * @export
 */
export const ListsApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {CheckList} list 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listsCreateList(list: CheckList, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<CheckList> {
            const localVarFetchArgs = ListsApiFetchParamCreator(configuration).listsCreateList(list, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listsGetAllList(options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Array<CheckList>> {
            const localVarFetchArgs = ListsApiFetchParamCreator(configuration).listsGetAllList(options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @param {string} listId 
         * @param {Date} [timestamp] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listsGetList(listId: string, timestamp?: Date, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<CheckList> {
            const localVarFetchArgs = ListsApiFetchParamCreator(configuration).listsGetList(listId, timestamp, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @param {string} listId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listsGetListEvents(listId: string, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<CheckList> {
            const localVarFetchArgs = ListsApiFetchParamCreator(configuration).listsGetListEvents(listId, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @param {string} listId 
         * @param {CheckList} list 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listsUpdateList(listId: string, list: CheckList, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Array<CheckList>> {
            const localVarFetchArgs = ListsApiFetchParamCreator(configuration).listsUpdateList(listId, list, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * ListsApi - factory interface
 * @export
 */
export const ListsApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * 
         * @param {CheckList} list 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listsCreateList(list: CheckList, options?: any) {
            return ListsApiFp(configuration).listsCreateList(list, options)(fetch, basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listsGetAllList(options?: any) {
            return ListsApiFp(configuration).listsGetAllList(options)(fetch, basePath);
        },
        /**
         * 
         * @param {string} listId 
         * @param {Date} [timestamp] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listsGetList(listId: string, timestamp?: Date, options?: any) {
            return ListsApiFp(configuration).listsGetList(listId, timestamp, options)(fetch, basePath);
        },
        /**
         * 
         * @param {string} listId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listsGetListEvents(listId: string, options?: any) {
            return ListsApiFp(configuration).listsGetListEvents(listId, options)(fetch, basePath);
        },
        /**
         * 
         * @param {string} listId 
         * @param {CheckList} list 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listsUpdateList(listId: string, list: CheckList, options?: any) {
            return ListsApiFp(configuration).listsUpdateList(listId, list, options)(fetch, basePath);
        },
    };
};

/**
 * ListsApi - object-oriented interface
 * @export
 * @class ListsApi
 * @extends {BaseAPI}
 */
export class ListsApi extends BaseAPI {
    /**
     * 
     * @param {CheckList} list 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ListsApi
     */
    public listsCreateList(list: CheckList, options?: any) {
        return ListsApiFp(this.configuration).listsCreateList(list, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ListsApi
     */
    public listsGetAllList(options?: any) {
        return ListsApiFp(this.configuration).listsGetAllList(options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @param {string} listId 
     * @param {Date} [timestamp] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ListsApi
     */
    public listsGetList(listId: string, timestamp?: Date, options?: any) {
        return ListsApiFp(this.configuration).listsGetList(listId, timestamp, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @param {string} listId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ListsApi
     */
    public listsGetListEvents(listId: string, options?: any) {
        return ListsApiFp(this.configuration).listsGetListEvents(listId, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @param {string} listId 
     * @param {CheckList} list 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ListsApi
     */
    public listsUpdateList(listId: string, list: CheckList, options?: any) {
        return ListsApiFp(this.configuration).listsUpdateList(listId, list, options)(this.fetch, this.basePath);
    }

}

/**
 * WeatherForecastApi - fetch parameter creator
 * @export
 */
export const WeatherForecastApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        weatherForecastGet(options: any = {}): FetchArgs {
            const localVarPath = `/WeatherForecast`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WeatherForecastApi - functional programming interface
 * @export
 */
export const WeatherForecastApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        weatherForecastGet(options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Array<WeatherForecast>> {
            const localVarFetchArgs = WeatherForecastApiFetchParamCreator(configuration).weatherForecastGet(options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * WeatherForecastApi - factory interface
 * @export
 */
export const WeatherForecastApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        weatherForecastGet(options?: any) {
            return WeatherForecastApiFp(configuration).weatherForecastGet(options)(fetch, basePath);
        },
    };
};

/**
 * WeatherForecastApi - object-oriented interface
 * @export
 * @class WeatherForecastApi
 * @extends {BaseAPI}
 */
export class WeatherForecastApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WeatherForecastApi
     */
    public weatherForecastGet(options?: any) {
        return WeatherForecastApiFp(this.configuration).weatherForecastGet(options)(this.fetch, this.basePath);
    }

}

